# Generated by Django 2.1.1 on 2018-11-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='media', verbose_name='Изображение'),
        ),
    ]
