# Generated by Django 2.1.1 on 2019-01-13 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190113_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='main_image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Автор', to='core.Image', verbose_name='Оновное изображение'),
        ),
        migrations.AddField(
            model_name='entity',
            name='main_image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Объект', to='core.Image', verbose_name='Оновное изображение'),
        ),
    ]
