# Generated by Django 2.1.1 on 2019-01-13 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190113_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='main_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Автор', to='core.Image', verbose_name='Оновное изображение'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='main_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Объект', to='core.Image', verbose_name='Оновное изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='image',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Entity', verbose_name='Объект'),
        ),
    ]
