# Generated by Django 2.1.1 on 2019-01-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190113_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='begin_date',
            field=models.DateField(blank=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='Дата окончания'),
        ),
    ]
