# Generated by Django 2.1.1 on 2019-01-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190113_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.TextField(verbose_name='Наименование')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='name_en',
            field=models.TextField(blank=True, default='', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_other',
            field=models.TextField(blank=True, default='', verbose_name='Name_other'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name_en',
            field=models.TextField(blank=True, default='', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name_other',
            field=models.TextField(blank=True, default='', verbose_name='Name_other'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name_en',
            field=models.TextField(blank=True, default='', verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name_other',
            field=models.TextField(blank=True, default='', verbose_name='Name_other'),
        ),
        migrations.AddField(
            model_name='entity',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.Category', verbose_name='Категория'),
        ),
    ]
