# Generated by Django 2.1.1 on 2019-03-17 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190317_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='main_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_authors', to='core.Image', verbose_name='Оновное изображение'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='main_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_entitys', to='core.Image', verbose_name='Оновное изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='entity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='images', to='core.Entity', verbose_name='Объект'),
        ),
    ]
