# Generated by Django 2.1.1 on 2019-03-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190317_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['name_ru']},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name_ru']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['name_ru']},
        ),
        migrations.AlterField(
            model_name='author',
            name='main_image',
            field=models.ImageField(blank=True, default=None, upload_to='media', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='authorsspecialization',
            name='specialization',
            field=models.TextField(choices=[('engraver', 'Гравер'), ('painter', 'Художник')], verbose_name='Специальность'),
        ),
    ]
