# Generated by Django 2.1.1 on 2019-04-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190324_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsspecialization',
            name='specialization',
            field=models.TextField(choices=[('engraver', 'Гравер'), ('painter', 'Художник'), ('publisher', 'Издатель')], verbose_name='Специальность'),
        ),
    ]
