# Generated by Django 2.1.1 on 2019-04-21 20:46
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190402_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumb_image',
            field=models.ImageField(default=None, null=True, upload_to='media/thumbs', verbose_name='Превью'),
        ),
    ]
