# Generated by Django 2.1.1 on 2019-04-21 20:46
from io import BytesIO
from PIL import Image as Pil_Image
import sys

from django.db import migrations
from django.core.files.uploadedfile import InMemoryUploadedFile


def make_thumbs(apps, schema_editor):
    Image = apps.get_model('core', 'Image')
    error_images = []
    for image in Image.objects.all():
        if image.image:
            try:
                img = Pil_Image.open(image.image)
                output = BytesIO()
                img.thumbnail((img.width // 10, img.height // 10))
                img.save(output, format='JPEG', quality=100)
                output.seek(0)
                image.thumb_image = InMemoryUploadedFile(
                    output,
                    'ImageField',
                    "%s.jpg" % image.image.name.split('.')[0],
                    'image/jpeg',
                    sys.getsizeof(output),
                    None,
                )
                image.save()
            except OSError:
                error_images.append(image.pk)
    print(error_images)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_image_thumb_image'),
    ]

    operations = [
        migrations.RunPython(make_thumbs),
    ]
