# Generated by Django 2.1.1 on 2019-04-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fill_image_thumb_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='create_data',
        ),
        migrations.AddField(
            model_name='image',
            name='create_date',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='author',
            name='begin_date',
            field=models.TextField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='end_date',
            field=models.TextField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='author',
            name='index',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_other',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Name_other'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='author',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='begin_date',
            field=models.TextField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='index',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name_other',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Name_other'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='source',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description_lat',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание lat'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name_other',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Name_other'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='image',
            name='notes',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='image',
            name='source_link',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на источник'),
        ),
    ]
