# Generated by Django 2.1.1 on 2019-04-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190426_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='source_link',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на источник'),
        ),
    ]
