# Generated by Django 2.1.1 on 2019-04-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_author_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.TextField(verbose_name='Страна')),
                ('name_en', models.TextField(verbose_name='Land')),
            ],
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.TextField(verbose_name='Название специализации')),
                ('name_en', models.TextField(verbose_name='Occupation')),
            ],
        ),
        migrations.RemoveField(
            model_name='authoralias',
            name='author',
        ),
        migrations.RemoveField(
            model_name='author',
            name='name_other',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='name_other',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_other',
        ),
        migrations.AddField(
            model_name='author',
            name='begin_work_date',
            field=models.TextField(blank=True, null=True, verbose_name='Дата начала деятельности'),
        ),
        migrations.AddField(
            model_name='author',
            name='end_work_date',
            field=models.TextField(blank=True, null=True, verbose_name='Дата окончания деятельности'),
        ),
        migrations.AddField(
            model_name='author',
            name='gnd',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Индекс GND'),
        ),
        migrations.AddField(
            model_name='entity',
            name='normdate',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Нормативный контроль'),
        ),
        migrations.AddField(
            model_name='image',
            name='catalog_links',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ссылки на каталоги'),
        ),
        migrations.AddField(
            model_name='image',
            name='doublet_links',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ссылки на дублеты'),
        ),
        migrations.AddField(
            model_name='image',
            name='index_image_hab',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Индекс в коллеции HAB'),
        ),
        migrations.AddField(
            model_name='image',
            name='index_image_mu',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Индекс в коллеции'),
        ),
        migrations.AddField(
            model_name='image',
            name='size',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='image',
            name='technique',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Техника исполнения'),
        ),
        migrations.DeleteModel(
            name='AuthorAlias',
        ),
        migrations.AddField(
            model_name='author',
            name='lands',
            field=models.ManyToManyField(related_name='authors', to='core.Land', verbose_name='Страны творчества'),
        ),
        migrations.AddField(
            model_name='author',
            name='occupations',
            field=models.ManyToManyField(related_name='authors', to='core.Occupation', verbose_name='Специализации'),
        ),
    ]
