# Generated by Django 2.1.1 on 2019-05-01 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20190429_0019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('name_ru', 'name_en', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('name_ru', 'name_en', 'index')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('name_ru', 'name_en', 'index_image_mu')},
        ),
    ]
